### ISSUE TITLE
Transfer ownership to pytoolz organisation?

### ISSUE THREAD

**Issue by davidshepherd7** [mrocklin/toolz#16]
Currently github thinks that this repository is the main fork of toolz. This can be mildly annoying, e.g. because [`hub compare`](https://github.com/github/hub) creates comparisons against this fork instead of the main one.

It could also put off potential new users because this fork is comparatively dead: no commits for 6 months, and much fewer forks and stars.

You can [transfer](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization) ownership fairly easily so it might be worth doing. (Apologies if you already knew this and are choosing not to transfer it for some reason.)

**Comment by mrocklin** [comment]
This is done.
